spring:
  config:
    activate:
      on-profile:
        - default
  datasource:
    url: jdbc:mysql://localhost:3306/digiday
    username: root
    password: mysql
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  output:
    ansi:
      enabled: ALWAYS
  security:
    ignored:
      - "*.bundle.*"
    user:
      password: password

server:
  port: 80
